### ISSUE TITLE
Travis fails when working on the 324pb_support branch

### ISSUE THREAD

**Issue by MCUdude** [MCUdude/MightyCore#103]
It seems like Travis [has some issues](https://travis-ci.org/MCUdude/MightyCore) with the 324pb_support branch. Can you look into this @per1234 ? 🙂

**Comment by MCUdude** [comment]
Thanks!

**Comment by MCUdude** [comment]
Seems like the latest merge is causing some issues @per1234

**Comment by per1234** [comment]
I don't think that's caused by a problem with MightyCore or with the Travis CI configuration. It's a failure of Travis CI to check out the branch of the repository. That could either be a glitch in Travis CI or maybe it's just the expected and correct result in this particular situation. I think [build 59](https://travis-ci.org/MCUdude/MightyCore/builds/403878658) is the important one so let's see how that goes.

**Comment by MCUdude** [comment]
Seems like build 59 succeeded!
