### ISSUE TITLE
IRremote library not working 

### ISSUE THREAD

**Issue by mhdfasilwyd** [MCUdude/MightyCore#16]
Pls make Mighty core supported IRremote library

**Comment by MCUdude** [comment]
I'll take a look at it, but I'll need to know what kind of microcontroller are you using.

**Comment by mhdfasilwyd** [comment]
Iam Using Atmega16 & 32

**Comment by MCUdude** [comment]
The library now compiles using ATmega8535, ATmega16 and ATmega32 (They are almost identical except for the memory). Please replace your **IRremoteInt.h** with the one I've attached. I'm going to do a pull request to the IRremote repository so that this fix will be incorporated.


If you're curious about which changes I did, Have a look at line 193/194 and 279/280 :) The only IR pin you can use on these microcontrollers are digital pin 13.

[IRremoteInt.h.zip](https://github.com/MCUdude/MightyCore/files/159069/IRremoteInt.h.zip)

**Comment by mhdfasilwyd** [comment]
It is because that this have only one timer

**Comment by MCUdude** [comment]
Yes. Timer2 was the default timer, but there are no Timer2A and Timer2B, only Timer2. The ATmega8535/16/32 and the ATmega8 are quite similar when it comes to internal registers, so usually the ATmega8 configuration will work

**Comment by mhdfasilwyd** [comment]
It worked thanks a lot MCUdude
